"""optimize notification model

Revision ID: 60f69d0898c8
Revises: 
Create Date: 2026-08-24 07:55:31.623881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f69d0898c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('via', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('passed_filter', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_company'), 'internships', ['company'], unique=False)
    op.create_index('ix_internships_company_created', 'internships', ['company', 'created_at'], unique=False)
    op.create_index('ix_internships_filter_created', 'internships', ['passed_filter', 'created_at'], unique=False)
    op.create_index(op.f('ix_internships_id'), 'internships', ['id'], unique=False)
    op.create_index('ix_internships_last_seen', 'internships', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_internships_url'), 'internships', ['url'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'company', 'domain', name='uq_subscription_user_company_domain')
    )
    op.create_index('ix_subscriptions_active', 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_company'), 'subscriptions', ['company'], unique=False)
    op.create_index('ix_subscriptions_company_domain_active', 'subscriptions', ['company', 'domain', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_domain'), 'subscriptions', ['domain'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_email'), 'subscriptions', ['user_email'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', name='notificationstatus', native_enum=False, length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'internship_id', name='uq_notification_user_internship')
    )
    op.create_index('ix_notifications_dispatch', 'notifications', ['next_retry_at', 'created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_notifications_internship_id'), 'notifications', ['internship_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_email', 'status', 'created_at'], unique=False)
    op.create_index('ix_notifications_zombie_recovery', 'notifications', ['processing_started_at'], unique=False, postgresql_where=sa.text("status = 'PROCESSING'"))
    op.create_index('uq_notifications_idempotency_key', 'notifications', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_idempotency_key', table_name='notifications', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_notifications_zombie_recovery', table_name='notifications', postgresql_where=sa.text("status = 'PROCESSING'"))
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_internship_id'), table_name='notifications')
    op.drop_index('ix_notifications_dispatch', table_name='notifications', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('notifications')
    op.drop_index(op.f('ix_subscriptions_user_email'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_domain'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_company_domain_active', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_company'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_active', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_internships_url'), table_name='internships')
    op.drop_index('ix_internships_last_seen', table_name='internships')
    op.drop_index(op.f('ix_internships_id'), table_name='internships')
    op.drop_index('ix_internships_filter_created', table_name='internships')
    op.drop_index('ix_internships_company_created', table_name='internships')
    op.drop_index(op.f('ix_internships_company'), table_name='internships')
    op.drop_table('internships')
    # ### end Alembic commands ###
