"""Add internship dismissals

Revision ID: b03db025e262
Revises: e014ab53d82d
Create Date: 2026-09-17 08:19:32.266356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03db025e262'
down_revision: Union[str, Sequence[str], None] = 'e014ab53d82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'internship_id', name='uq_internship_dismissal_user_internship')
    )
    op.create_index(op.f('ix_internship_dismissals_id'), 'internship_dismissals', ['id'], unique=False)
    op.create_index(op.f('ix_internship_dismissals_internship_id'), 'internship_dismissals', ['internship_id'], unique=False)
    op.create_index('ix_internship_dismissals_user', 'internship_dismissals', ['user_email', 'dismissed_at'], unique=False)
    op.create_index(op.f('ix_internship_dismissals_user_email'), 'internship_dismissals', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internship_dismissals_user_email'), table_name='internship_dismissals')
    op.drop_index('ix_internship_dismissals_user', table_name='internship_dismissals')
    op.drop_index(op.f('ix_internship_dismissals_internship_id'), table_name='internship_dismissals')
    op.drop_index(op.f('ix_internship_dismissals_id'), table_name='internship_dismissals')
    op.drop_table('internship_dismissals')
    # ### end Alembic commands ###
