"""add subscription status

Revision ID: e014ab53d82d
Revises: fe925e47d43c
Create Date: 2026-09-06 17:26:50.110217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e014ab53d82d'
down_revision: Union[str, Sequence[str], None] = 'fe925e47d43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    

    op.add_column(
        'subscriptions',
        sa.Column(
            'status',
            sa.Enum(
                'ACTIVE',
                'PAUSED',
                'CANCELLED',
                name='subscription_status',
                create_type=False
            ),
            nullable=False,
            server_default='ACTIVE'
        )
    )

    op.alter_column(
        'subscriptions',
        'status',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
