"""remove duplicate subscription active index

Revision ID: fe925e47d43c
Revises: 60f69d0898c8
Create Date: 2026-09-06 15:39:46.163907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe925e47d43c'
down_revision: Union[str, Sequence[str], None] = '60f69d0898c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_active'), table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscriptions_active'), 'subscriptions', ['is_active'], unique=False)
    # ### end Alembic commands ###
